### ISSUE TITLE
unable to install after update

### ISSUE THREAD

**Issue by wkulesza** [BlinkTagInc/transit-arrivals-widget#5]
Hi,
after updating (and even now when git cloning 0.1.4 tag), i'm getting this error after clone, edit of config.json and running npm install:

```
root@vpsXXXXX:/home/wojciech/transit-arrivals-widget# npm install transit-arrivals-widget --unsafe-perm --allow-root -g
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://git@github.com/mapbox/node-sqlite3.git /root/.npm/_cacache/tmp/git-clone-f290504d/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-f290504d/.git'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-16T19_30_05_191Z-debug.log
```

Please help. When trying to git clone and then npm install as normal user, im getting errors as normal user has access to node v8.10.0 only and other errors popup like: Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/transit-arrivals-widget

**Comment by brendannee** [comment]
Try the version 1.0.1 that I just released and see if that solves the issue.

**Comment by wkulesza** [comment]
I just tried and now getting:
```
root@srv1:/opt/transit-arrivals-widget# npm install transit-arrivals-widget --unsafe-perm --allow-root -g
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v16.11.1/lib/node_modules/transit-arrivals-widget/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! sh: node-pre-gyp: command not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-17T21_01_21_525Z-debug.log
root@srv1:/opt/transit-arrivals-widget# transit-arrivals-widget
transit-arrivals-widget: command not found
```

using:
nvm 0.39.0
npm 8.1.0
node v16.11.1

**Comment by brendannee** [comment]
Thanks for trying this.

The sqlite3 library in use relies on an older version of node-pre-gyp which hasn't added support for node 16 yet. I'll release a new version once all of these dependencies get updates.

The issue could actually be the version of npm - I see other people mentioning issues with npm > 6, so trying node 16 with npm 6 may work.

**Comment by wkulesza** [comment]
OK, will translate.
Does this string need to be moved to template too ?
"To" - in the listing of upcoming arrivals, next to route number, before trip headsign ?

It is still not-stable for me, as sometimes, there's no arrivals presented for a trip that is correct (i.e. I can see it in other gtfs-rt consuming apps) but here, i need to refresh whole page to see the result.
The only issue I can see in console is (this displays in polish, so translating it to english):
Color expected but found "#null". Error processing values for 'background-color'. Declaration abandoned.
Color expected but found "#null". Error processing value for "color". Declaration abandoned.
